### PR TITLE
Add pyproject.toml

### PR DESCRIPTION
**Pull request by magnusuMET**
* Adds dependencies such that pip can resolve them
* Replaces deprecated import `pkg_resources` for use by python 3.12 and up

### CODE REVIEW

**Comment by jgliss** [comment]
@magnusuMET thanks for this PR. Could you describe in a little more detail why you suggest this change and what benefits it brings over using setup.py?

Also, will it affect the conda release recipe: https://github.com/jgliss/geonum-feedstock/blob/master/recipe/meta.yaml?

Cheers to MET :-)

**Comment by jgliss** [comment]
Please also note #25 which should fix the pipeline once it's merged :)

**Comment by magnusuMET** [comment]
`setup.py` does not allowing specifying dependencies, meaning `pip` can not resolve and install them for us. That means downstream users has to keep track of the dependencies of this package and manually install them (add them to their pyproject etc., requirements). Having this functionality means a `pip install` is as simple as the way one can install through conda.

I do not think the move to `pyproject.toml` should affect the conda recipie

**Comment by jgliss** [comment]
Looks good now, thanks @magnusuMET

**Pull request merged**
